# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define :Rohrrechner
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision :shell, path: "initialise.sh"
  config.vm.synced_folder "../", "/var/www/html"
end
